language: node_js

node_js:
  - '8'

services:
  - postgresql

cache:
  directories:
  - node_modules

install:
  - npm install
  - npm run bootstrap

script:
  - (./node_modules/.bin/jest --coverage --coverageReporters=text-lcov | ./node_modules/.bin/coveralls; exit ${PIPESTATUS[0]})